# Demostración: Widgets Bien Configurados
services:
  - Download Tools:
      - Jackett Indexer:
          href: http://jackett.demo:9117
          description: Torrent indexer service
          icon: jackett.png
          widget:
            type: jackett
            url: http://jackett.demo:9117
            username: admin
            password: secretpass

      - Transmission:
          href: http://transmission.demo:9091
          description: Download client
          icon: transmission.png
          widget:
            type: transmission
            url: http://transmission.demo:9091
            username: admin
            password: admin

  - Media Management:
      - Sonarr TV:
          href: http://sonarr.demo:8989
          description: TV series management
          icon: sonarr.png
          widget:
            type: sonarr
            url: http://sonarr.demo:8989
            key: sonarr-api-key-example
            enableQueue: true

widgets:
  - search:
      provider: google
      target: _blank

bookmarks:
  - Demo Links:
      - Homepage Docs:
          href: https://gethomepage.dev
          description: Official documentation
